config/routes.rb
ITour::Application.routes.draw do
  resources :deals
  
  match "/tasks(/:site)(/:type)" => Task.action(:index)
  
  mount Resque::Server, :at => "/resque"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :image, :intro, :price, :provider, :catalog, :url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /deals
  # GET /deals.json
  def index
    @deals = Deal.paginate(:page => params[:page], :per_page => 12)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @deals }
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
    @deal = Deal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/new
  # GET /deals/new.json
  def new
    @deal = Deal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @deal }
    end
  end

  # GET /deals/1/edit
  def edit
    @deal = Deal.find(params[:id])
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /deals/1
  # PUT /deals/1.json
  def update
    @deal = Deal.find(params[:id])

    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal = Deal.find(params[:id])
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :intro %><br />
    <%= f.text_area :intro %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<div class="apple_pagination"><%= will_paginate %></div>
<div class="deals">
<% @deals.each do |deal| %>
	<div class="deal">
		<div class="intro"><%= deal.intro %></div>
		<div class="image">
			<%= link_to deal.url do%>
				<img src="<%= deal.image %>" width="300" height="200" />
			<% end %>
		</div>
		<div class="price"><%= deal.price %></div>
	</div>
<% end %>
</div>

<div class="footer">
	<%= link_to 'New Deal', new_deal_path %>
	<%= link_to 'View Task', resque_server_path %>
</div>

app/views/deals/new.html.erb
<h1>New deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @deal.url %>
</p>

<p>
  <b>Intro:</b>
  <%= @deal.intro %>
</p>

<p>
  <b>Price:</b>
  <%= @deal.price %>
</p>

<p>
  <b>Type:</b>
  <%= @deal.type %>
</p>

<p>
  <b>Provider:</b>
  <%= @deal.provider %>
</p>


<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ITour</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/rack_common.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ITour</title>
	<%= javascript_include_tag "application" %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/task/index.html.erb
<% @sites.each do|site, links|%>
	<ul><%= site %>
		<% links.each do |type, urls| %>
		<li><%= link_to type, "/tasks/#{site.downcase}/#{type}", remote: true %></li>
		<%end%>				
	</ul>
<% end %>

<div>
	<%#= link_to 'View Task', resque_server_path %>
</div>